### PR TITLE
Replaced raw_input with input in ucsfirmware.py

### PR DESCRIPTION
**Pull request by ryaeng**
raw_input is no lon…ger supported by Python 3.

### CODE REVIEW

**Comment by vvb** [comment]
@ryaeng are `pip-selfcheck.json` and `include/python2.7` required?? The rest looks good to me.

**Comment by arusrini** [comment]
One possible issue is with input() and given that this code is also expected to work with python 2.7, is the inherent security hole with the 2.7 version of input() - which executes an eval() allowing for command execution.

**Comment by vvb** [comment]
@arusrini yes, `input` in Python 2.x is `eval(raw_input())`. But, I am assuming it should be ok in this case, because 
1. This is not a process directly running on the Ucs Server/FI. 
2. This is not exposed as an Web/REST API and the input needs to be manually provided. So, I am guessing that the person doing the firmware upgrade will be the person passing this input. Hypothetically, this person can pass a entire python script as a string which wipes out Ucs_config to `input` and it will get executed too. But the person running firmware upgrade anyway has the access to run the script directly if he/she so desires.
- My 2 cents..

**Comment by ryaeng** [comment]
@vvb They are not required.  Would the best way to exclude those be to include them inside of .gitignore?

**Comment by vvb** [comment]
@ryaeng A lot of times I specify the files I want to commit and leave out some changes..
`git commit -m "comment" file1 file2`

**Comment by ryaeng** [comment]
Okay.  Is there a way to modify a commit?  The way I did it last was I deleted the commit and made the changes.

**Comment by vvb** [comment]
`git`  always has multiple ways of doing any single thing. :-)

Do the below for the 2 files that need to be removed,
`git rm <file>`
`git commit <file>`

Now, you can squash your commits into one single commit
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

then you can do a `git push origin replace_raw_input_in_ucsfirmware`
and you will see that this PR will be automatically updated.

**Comment by ryaeng** [comment]
@vvb Ran through the instructions as directed.  I'm now seeing the following.

To git@github.com:ryaeng/ucsmsdk_samples
 ! [rejected]        replace_raw_input_in_ucsfirmware -> replace_raw_input_in_ucsfirmware (non-fast-forward)
error: failed to push some refs to 'git@github.com:ryaeng/ucsmsdk_samples'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I could force it, but that doesn't seem to be best practice.

**Comment by vvb** [comment]
@ryaeng you probably need to force it in this scenario

**Comment by vvb** [comment]
@ryaeng looks like something is off.. a lot of other commits are also showing up here. some of them made by @ragupta-git .. time to `git reset` to the sha before your initial commit and applying your changes alone and re-committing the change.

**Comment by ryaeng** [comment]
@vvb I think I finally got it.  Hopefully everything looks good.

**Comment by vvb** [comment]
@ryaeng LGTM

**Pull request merged**
